/* 增加纯回头草QT预测模块 */
CREATE TABLE `stock_qt_ureturn_hold` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(255) DEFAULT NULL COMMENT '股票代码',
  `time_create` timestamp NULL DEFAULT NULL,
  `time_update` timestamp NULL DEFAULT NULL,
  `status` int(11) DEFAULT 0 COMMENT '状态，0未购买、1购买中、2暂停购买、3已购买、4卖出中、5暂定卖出、6交易结束、7交易失败',
  `buy_amount` int(11) DEFAULT 0 COMMENT '买入股票数',
  `buy_price` float DEFAULT 0 COMMENT '成本价格',
  `hold_amount` int(11) DEFAULT 0 COMMENT '持有股票数',
  `sell_stage` int(11) DEFAULT 0 COMMENT '卖出阶段，-1止损阶段，0初始阶段，1止盈1阶段，2止盈2阶段',
  `weekly_ema_result_id` int(11) DEFAULT NULL COMMENT '关联的ema_result_id',
  `note` varchar(500) DEFAULT '' COMMENT '备注',
  `price_close` float DEFAULT 0 COMMENT '昨日收盘价',
  `price_high` float DEFAULT 0 COMMENT '近期最高价',
  `price_low` float DEFAULT 0 COMMENT '近期最低价',
  `enhance_white_sign` tinyint(1) DEFAULT 0 COMMENT '是否发出增强白信号, 0未发出，1已发出',
  `lose_enhance_white_sign` tinyint(1) DEFAULT 0 COMMENT '是否失去增强白信号, 0未失去，1已失去',
  `price_sell_high` float DEFAULT 0 COMMENT '下一阶段价格或者是卖出最高价阀值',
  `price_sell_low` float DEFAULT 0 COMMENT '卖出最低价阀值',
  `close_ema_18` float DEFAULT 0 COMMENT '最近一个交易日的close_ema_18值',
  `price_stop` float DEFAULT 0 COMMENT '止损价格',
  `generate_type` int(11) DEFAULT 0 COMMENT '加入方式，0直接，1回头草，2加强回头草',
  `buy_total` float DEFAULT 0 COMMENT '买入总金额',
  `buy_fee` float DEFAULT 0 COMMENT '买入手续费',
  `time_buy` timestamp NULL DEFAULT NULL COMMENT '购买时间',
  `time_sell` timestamp NULL DEFAULT NULL COMMENT '卖出时间',
  `buy_rule_id` int(11) DEFAULT NULL COMMENT '买入策略id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `stock_qt_ureturn_hold_bonus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(10) DEFAULT NULL COMMENT '股票代码',
  `donate_rate` float DEFAULT 0 COMMENT '送股比例',
  `increase_rate` float DEFAULT 0 COMMENT '转增比例',
  `bonus_rate` float DEFAULT 0 COMMENT '派息比例',
  `date_register` varchar(20) DEFAULT NULL COMMENT '股权登记日',
  `date_ex_right` varchar(20) DEFAULT NULL COMMENT '除权日期',
  `date_ex_bonus` varchar(20) DEFAULT NULL COMMENT '除息日',
  `bonus_note` varchar(255) DEFAULT NULL COMMENT '分红说明',
  `bonus_type` varchar(20) DEFAULT NULL COMMENT '分红类型(年度分红/中期分红)',
  `date_report` varchar(20) DEFAULT NULL COMMENT '报告时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `stock_qt_ureturn_hold_trade` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hold_id` int(11) unsigned NOT NULL,
  `code` varchar(255) NOT NULL DEFAULT '',
  `amount` int(11) DEFAULT 100 COMMENT '委托数量',
  `trade_type` int(11) DEFAULT 0 COMMENT '交易类型：0买入，1卖出，2买入撤销，3卖出撤销，4分红配送',
  `trade_note` varchar(500) DEFAULT NULL COMMENT '交易备注',
  `orderid` varchar(50) DEFAULT NULL COMMENT '委托合同编号',
  `message` varchar(1000) DEFAULT NULL COMMENT '委托/撤单状态信息',
  `status` int(11) DEFAULT NULL COMMENT '委托/撤单状态，1结束，0执行中，-1失败',
  `note` varchar(1000) DEFAULT NULL COMMENT '投资备注',
  `taskid` varchar(50) DEFAULT NULL COMMENT '任务/指令编号',
  `taskstatus` int(11) DEFAULT NULL COMMENT '任务/指令状态，0 未知,1 等待,2 提交中,3 执行中,4 暂停,5 撤销中,6 异常撤销中,7 完成,8 已撤,9 打回,10  异常终止,11  放弃，目前用于组合交易中，放弃补单,12  强制终止',
  `taskmsg` varchar(1000) DEFAULT NULL COMMENT '任务/指令状态信息',
  `taskpro` varchar(500) DEFAULT NULL COMMENT '任务进度',
  `ordernum` varchar(50) DEFAULT NULL COMMENT '订单编号',
  `time_create` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `time_update` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `price` float DEFAULT 1,
  `counter` int(11) DEFAULT 0 COMMENT '查询结果计数器，默认为0',
  `price_type` varchar(10) DEFAULT '1' COMMENT '委托价格类型：1最新价、2对手价、3指定价、B1买1价、B2买2价、S1卖1价、S2卖2价',
  `cj_price` float DEFAULT 0 COMMENT '成交价格',
  `cj_amount` int(11) DEFAULT 0 COMMENT '成交数量',
  `cj_time` varchar(20) DEFAULT NULL COMMENT '成交时间',
  `cj_fee` float DEFAULT NULL COMMENT '成交手续费',
  `cj_total` float DEFAULT NULL COMMENT '成交金额',
  PRIMARY KEY (`id`),
  KEY `hold_id_fk` (`hold_id`),
  CONSTRAINT `stock_qt_ureturn_hold_trade_ibfk_2` FOREIGN KEY (`hold_id`) REFERENCES `stock_qt_ureturn_hold` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `stock_qt_ureturn_profit` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hold_id` int(11) NOT NULL COMMENT '股票池id',
  `date_research` varchar(8) NOT NULL DEFAULT '' COMMENT '盈亏调研日期',
  `code` varchar(255) NOT NULL DEFAULT '' COMMENT '股票代码',
  `price_close` float DEFAULT 0 COMMENT '收盘价',
  `amount_hold` int(11) DEFAULT 0 COMMENT '持股数',
  `total` float DEFAULT 0 COMMENT '总市值',
  `time_create` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `profit` float DEFAULT 0 COMMENT '盈亏值',
  `profit_rate` float DEFAULT 0 COMMENT '盈亏率',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `stock_qt_ureturn_profit_hold` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hold_id` int(11) NOT NULL COMMENT '股票池id',
  `code` varchar(255) NOT NULL DEFAULT '' COMMENT '股票代码',
  `total_begin` float DEFAULT 0 COMMENT '成本',
  `time_create` timestamp NULL DEFAULT NULL,
  `profit` float DEFAULT 0 COMMENT '盈亏值',
  `profit_rate` float DEFAULT 0 COMMENT '盈亏率',
  `time_buy` timestamp NULL DEFAULT NULL COMMENT '购买时间',
  `time_sell` timestamp NULL DEFAULT NULL COMMENT '清仓时间',
  `hold_days` int(11) DEFAULT 1 COMMENT '持股天数',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

