# 通过spring.profiles.active 激活了dev选项，则项目运行或调试启动时会根据该项配置读取application-dev中的内容
# 项目通过maven进行打包发行，启动时通过启动参数锁定运行配置文件 java -jar ghk-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
